export interface Team {
  code: string;
  name: string; // Hebrew
  flag: string; // emoji (fallback)
  iso: string; // ISO 3166-1 alpha-2 for flag images
}

export const teams: Team[] = [
  { code: "MAR", name: "מרוקו", flag: "🇲🇦", iso: "ma" },
  { code: "USA", name: "ארה״ב", flag: "🇺🇸", iso: "us" },
  { code: "CAN", name: "קנדה", flag: "🇨🇦", iso: "ca" },
  { code: "MEX", name: "מקסיקו", flag: "🇲🇽", iso: "mx" },
  { code: "ARG", name: "ארגנטינה", flag: "🇦🇷", iso: "ar" },
  { code: "AUS", name: "אוסטרליה", flag: "🇦🇺", iso: "au" },
  { code: "BEL", name: "בלגיה", flag: "🇧🇪", iso: "be" },
  { code: "BRA", name: "ברזיל", flag: "🇧🇷", iso: "br" },
  { code: "CMR", name: "קמרון", flag: "🇨🇲", iso: "cm" },
  { code: "COL", name: "קולומביה", flag: "🇨🇴", iso: "co" },
  { code: "CRC", name: "קוסטה ריקה", flag: "🇨🇷", iso: "cr" },
  { code: "CRO", name: "קרואטיה", flag: "🇭🇷", iso: "hr" },
  { code: "DEN", name: "דנמרק", flag: "🇩🇰", iso: "dk" },
  { code: "ECU", name: "אקוודור", flag: "🇪🇨", iso: "ec" },
  { code: "ENG", name: "אנגליה", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", iso: "gb-eng" },
  { code: "FRA", name: "צרפת", flag: "🇫🇷", iso: "fr" },
  { code: "GER", name: "גרמניה", flag: "🇩🇪", iso: "de" },
  { code: "GHA", name: "גאנה", flag: "🇬🇭", iso: "gh" },
  { code: "HON", name: "הונדורס", flag: "🇭🇳", iso: "hn" },
  { code: "HUN", name: "הונגריה", flag: "🇭🇺", iso: "hu" },
  { code: "IRN", name: "איראן", flag: "🇮🇷", iso: "ir" },
  { code: "ITA", name: "איטליה", flag: "🇮🇹", iso: "it" },
  { code: "JPN", name: "יפן", flag: "🇯🇵", iso: "jp" },
  { code: "KOR", name: "דרום קוריאה", flag: "🇰🇷", iso: "kr" },
  { code: "KSA", name: "ערב הסעודית", flag: "🇸🇦", iso: "sa" },
  { code: "MAL", name: "מאלי", flag: "🇲🇱", iso: "ml" },
  { code: "NED", name: "הולנד", flag: "🇳🇱", iso: "nl" },
  { code: "NGA", name: "ניגריה", flag: "🇳🇬", iso: "ng" },
  { code: "NZL", name: "ניו זילנד", flag: "🇳🇿", iso: "nz" },
  { code: "PAN", name: "פנמה", flag: "🇵🇦", iso: "pa" },
  { code: "PAR", name: "פרגוואי", flag: "🇵🇾", iso: "py" },
  { code: "PER", name: "פרו", flag: "🇵🇪", iso: "pe" },
  { code: "POL", name: "פולין", flag: "🇵🇱", iso: "pl" },
  { code: "POR", name: "פורטוגל", flag: "🇵🇹", iso: "pt" },
  { code: "QAT", name: "קטאר", flag: "🇶🇦", iso: "qa" },
  { code: "SCO", name: "סקוטלנד", flag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿", iso: "gb-sct" },
  { code: "SEN", name: "סנגל", flag: "🇸🇳", iso: "sn" },
  { code: "SER", name: "סרביה", flag: "🇷🇸", iso: "rs" },
  { code: "SLO", name: "סלובניה", flag: "🇸🇮", iso: "si" },
  { code: "ESP", name: "ספרד", flag: "🇪🇸", iso: "es" },
  { code: "SUI", name: "שוויץ", flag: "🇨🇭", iso: "ch" },
  { code: "TUN", name: "תוניסיה", flag: "🇹🇳", iso: "tn" },
  { code: "TUR", name: "טורקיה", flag: "🇹🇷", iso: "tr" },
  { code: "UKR", name: "אוקראינה", flag: "🇺🇦", iso: "ua" },
  { code: "URU", name: "אורוגוואי", flag: "🇺🇾", iso: "uy" },
  { code: "WAL", name: "ויילס", flag: "🏴󠁧󠁢󠁷󠁬󠁳󠁿", iso: "gb-wls" },
  { code: "EGY", name: "מצרים", flag: "🇪🇬", iso: "eg" },
  { code: "JAM", name: "ג׳מייקה", flag: "🇯🇲", iso: "jm" },
];
